# Generated by Django 6.0.3 on 2026-03-27 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('investor', 'Investor')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stage_order', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'deal_stages',
                'ordering': ['stage_order'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('client', 'Client')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('profile_photo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DealContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_contacts', to='crm.contact')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_contacts', to='crm.deal')),
            ],
            options={
                'db_table': 'deal_contacts',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='contacts',
            field=models.ManyToManyField(related_name='deals', through='crm.DealContact', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.deal')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='crm.dealstage')),
            ],
            options={
                'db_table': 'deal_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.dealstage'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('stage_change', 'Stage Change'), ('time_based', 'Time Based')], max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.deal')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='crm.emailtemplate')),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_builder', models.CharField(blank=True, max_length=255)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('property_class', models.CharField(blank=True, max_length=120)),
                ('building_type', models.CharField(blank=True, max_length=120)),
                ('property_style', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('block_lot', models.CharField(blank=True, max_length=120)),
                ('legal_plan', models.CharField(default='', max_length=120)),
                ('community', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('occupancy', models.CharField(blank=True, max_length=120)),
                ('condo_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_dom', models.IntegerField(blank=True, null=True)),
                ('dom', models.IntegerField(blank=True, null=True)),
                ('flooring', models.CharField(blank=True, max_length=120)),
                ('appliances_included', models.BooleanField(default=False)),
                ('jr_high_school', models.CharField(blank=True, max_length=255)),
                ('sr_high_school', models.CharField(blank=True, max_length=255)),
                ('garage_type', models.CharField(blank=True, max_length=120)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('basement', models.CharField(blank=True, max_length=120)),
                ('basement_dev', models.CharField(blank=True, max_length=120)),
                ('separate_entrance', models.BooleanField(default=False)),
                ('possession', models.CharField(blank=True, max_length=120)),
                ('landscaped', models.CharField(blank=True, max_length=120)),
                ('den_level', models.CharField(blank=True, max_length=120)),
                ('zero_lot_line', models.BooleanField(default=False)),
                ('floor_plan_url', models.URLField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_our_inventory', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-added_date'],
                'constraints': [models.UniqueConstraint(fields=('community', 'block_lot', 'legal_plan'), name='uq_property_community_block_legal')],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.property'),
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='crm.deal')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='crm.property')),
            ],
            options={
                'db_table': 'showings',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing_participation', to='crm.contact')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='crm.showing')),
            ],
            options={
                'db_table': 'showing_participants',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.user')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('type', models.CharField(choices=[('feature_sheet', 'Feature Sheet'), ('contract', 'Contract'), ('brochure', 'Brochure')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.deal')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.property')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='crm.user')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to='crm.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to='crm.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to='crm.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contacts', to='crm.user'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to='crm.user')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dealcontact',
            constraint=models.UniqueConstraint(fields=('deal', 'contact'), name='uq_deal_contact'),
        ),
        migrations.AddIndex(
            model_name='showing',
            index=models.Index(fields=['property', 'scheduled_at'], name='idx_showings_property_schedule'),
        ),
        migrations.AddConstraint(
            model_name='showingparticipant',
            constraint=models.UniqueConstraint(fields=('showing', 'contact'), name='uq_showing_contact'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_tasks_assigned_status'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['assigned_agent', 'stage'], name='idx_deals_agent_stage'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['assigned_to'], name='idx_contacts_assigned'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['deal', 'contact'], name='idx_activities_deal_contact'),
        ),
    ]
