# Generated by Django 6.0.3 on 2026-03-25 01:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('professional_role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('investor', 'Investor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('showing', 'Showing'), ('offer', 'Offer'), ('closed', 'Closed'), ('lost', 'Lost')], default='lead', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('access_role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('client', 'Client')], max_length=10)),
                ('professional_role', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('profile_photo', models.URLField(blank=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_banner', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DealContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_contacts', to='crm.contact')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_contacts', to='crm.deal')),
            ],
            options={
                'db_table': 'deal_contacts',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='contacts',
            field=models.ManyToManyField(related_name='deals', through='crm.DealContact', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_builder', models.CharField(blank=True, max_length=255)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('property_class', models.CharField(blank=True, max_length=120)),
                ('building_type', models.CharField(blank=True, max_length=120)),
                ('property_style', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('block_lot', models.CharField(blank=True, max_length=120)),
                ('legal_plan', models.CharField(default='', max_length=120)),
                ('community', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('occupancy', models.CharField(blank=True, max_length=120)),
                ('condo_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_dom', models.IntegerField(blank=True, null=True)),
                ('dom', models.IntegerField(blank=True, null=True)),
                ('flooring', models.CharField(blank=True, max_length=120)),
                ('appliances_included', models.BooleanField(default=False)),
                ('jr_high_school', models.CharField(blank=True, max_length=255)),
                ('sr_high_school', models.CharField(blank=True, max_length=255)),
                ('garage_type', models.CharField(blank=True, max_length=120)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('basement', models.CharField(blank=True, max_length=120)),
                ('basement_dev', models.CharField(blank=True, max_length=120)),
                ('separate_entrance', models.BooleanField(default=False)),
                ('possession', models.CharField(blank=True, max_length=120)),
                ('landscaped', models.CharField(blank=True, max_length=120)),
                ('den_level', models.CharField(blank=True, max_length=120)),
                ('zero_lot_line', models.BooleanField(default=False)),
                ('floor_plan_url', models.URLField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_our_inventory', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-added_date'],
                'constraints': [models.UniqueConstraint(fields=('community', 'block_lot', 'legal_plan'), name='uq_property_community_block_legal')],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.property'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='crm.contact')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.property')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to='crm.user')),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='agent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deals', to='crm.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to='crm.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contacts', to='crm.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to='crm.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contacts', to='crm.user'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('chat', 'Chat'), ('email', 'Email')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.contact')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.property')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_sent', to='crm.user')),
            ],
            options={
                'db_table': 'communications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('notes', 'Notes')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.contact')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.property')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to='crm.user')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='dealcontact',
            constraint=models.UniqueConstraint(fields=('deal', 'contact'), name='uq_deal_contact'),
        ),
    ]
